name: Flutter APK Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Recreate Android and Fix SDK Versions
        run: |
          rm -rf android
          flutter create . --platforms=android --project-name=ai_dost

          # app_links और gradle की एरर रोकने के लिए compileSdkVersion और namespace पक्का करते हैं
          BUILD_GRADLE="android/app/build.gradle"
          if [ -f "$BUILD_GRADLE" ]; then
            echo "Fixing build.gradle..."
            sed -i 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' $BUILD_GRADLE
            sed -i 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' $BUILD_GRADLE
            sed -i 's/targetSdkVersion flutter.targetSdkVersion/targetSdkVersion 34/g' $BUILD_GRADLE
          fi

      - name: Get Dependencies
        run: flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
