name: Flutter APK Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: 'stable'

      - name: Deep Clean and Override
        run: |
          find . -name "pubspec.lock" -delete
          find . -name ".dart_tool" -type d -exec rm -rf {} +
          rm -rf android ios windows macos linux
          flutter create . --platforms=android --project-name=ai_dost_app
          flutter pub get

      - name: Build APK Release
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
