name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Clone Flutter
        run: git clone https://github.com/flutter/flutter.git --branch stable --depth 1 ~/flutter

      - name: Add Flutter to Path
        run: echo "$HOME/flutter/bin" >> $GITHUB_PATH

      - name: Verify Flutter
        run: flutter --version

      - name: Generate Android Platform Files
        run: flutter create . --platforms=android

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
